apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bunkr-agent.fullname" . }}
  labels:
    {{- include "bunkr-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bunkr-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "bunkr-agent.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bunkr-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BUNKR_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bunkr-agent.fullname" . }}
                  key: client-secret
<<<<<<< HEAD
            - name: BUNKR_STORAGE_ACCOUNT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bunkr-agent.fullname" . }}
                  key: account-secret
=======
>>>>>>> 208b4e41c07a4a911f68f5f63b9693ab961cb593
            - name: BUNKR_API_URL
              value: {{ .Values.apiUrl | quote }}
            - name: BUNKR_API_CLIENT_ID
              value: {{ required "A valid .Values.clientId entry required!" .Values.clientId | quote }}
            - name: BUNKR_SOCKET_URL
              value: {{ .Values.socketUrl | quote }}
            - name: IDENTITY_PROVIDER_URL
              value: {{ .Values.identityProviderUrl | quote }}
<<<<<<< HEAD
            - name: IDENTITY_PROVIDER_AUDIENCE
              value: {{ .Values.identityProviderAudience | quote }}
=======
>>>>>>> 208b4e41c07a4a911f68f5f63b9693ab961cb593
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
