apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bunkr-agent.fullname" . }}
  labels:
    {{- include "bunkr-agent.labels" . | nindent 4 }}
type: Opaque
data:
  account-secret: {{ required "A valid .Values.accountSecret entry required!" .Values.accountSecret | b64enc | quote }}
  client-secret: {{ required "A valid .Values.clientSecret entry required!" .Values.clientSecret | b64enc | quote }}
