apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bunkr-agent.fullname" . }}
  labels:
    {{- include "bunkr-agent.labels" . | nindent 4 }}
type: Opaque
data:
<<<<<<< HEAD
  account-secret: {{ required "A valid .Values.accountSecret entry required!" .Values.accountSecret | b64enc | quote }}
=======
>>>>>>> 208b4e41c07a4a911f68f5f63b9693ab961cb593
  client-secret: {{ required "A valid .Values.clientSecret entry required!" .Values.clientSecret | b64enc | quote }}
